### ISSUE TITLE
Document\Page title property

### ISSUE THREAD

**Issue by dpfaffenbauer** [dachcom-digital/pimcore-seo#12]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

SEO disables the default Pimcore title and description fields, but it doesn't set these fields on save anymore. thus if you use them, they cannot be changed.

**Comment by solverat** [comment]
I'm not sure what you mean. If you're going to install the seo bundle within a existing project with existing defautl title and descriptions, the SEO-Bundle will migrate them:

1. **Add a default title & description to a pimcore page**:
![image](https://user-images.githubusercontent.com/700119/90002608-29559800-dc93-11ea-8eac-e83f11776aee.png)

2. **Enable SEO-Bundle.**

3. **Open the document in a frontend view, original title and description is still available**:
![image](https://user-images.githubusercontent.com/700119/90002748-5d30bd80-dc93-11ea-94b3-afd129ee01b0.png)

4. **Open the SEO-Tab, original title and descriptions are available**:
![image](https://user-images.githubusercontent.com/700119/90002716-52762880-dc93-11ea-9de9-1b46a0a3b074.png)

5. **Change those fields and finally the new data will be used.**

**Comment by dpfaffenbauer** [comment]
What I mean is, that you don't set the original values anymore, so document->getTitle returns the old value or a null value, the same with description. Since these fields are pimcore default, SEO Bundle should also set them.

**Comment by solverat** [comment]
Right, adding title and description on a pre-update event should do the job!
