### ISSUE TITLE
PHP API - title and description

### ISSUE THREAD

**Issue by mittererr** [dachcom-digital/pimcore-seo#15]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes

Is it possible to set meta title and description programmatically to an dataobject? In the docs I have read something about "smooth PHP-API". Is there any further information?

**Comment by solverat** [comment]
Yes. Just use a custom extractor (https://github.com/dachcom-digital/pimcore-seo/blob/master/docs/MetaData/Extractor/10_CustomExtractor.md).
