### ISSUE TITLE
Pimcore X compatibility

### ISSUE THREAD

**Issue by dpfahlbusch** [dachcom-digital/pimcore-seo#23]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? |no
| RFC?             | no

Currently this bundle is not compatible with Pimcore X.
If i try to install this bundle, i get the following error:

```
Problem 1
    - dachcom-digital/seo v1.1.0 requires pimcore/pimcore ^6.0.0 -> found pimcore/pimcore[v6.0.0, ..., v6.9.5] but it conflicts with your root composer.json require (^10.0).
    - dachcom-digital/seo v1.1.1 requires pimcore/pimcore ^6.0 -> found pimcore/pimcore[v6.0.0, ..., v6.9.5] but it conflicts with your root composer.json require (^10.0).
    - Root composer.json requires dachcom-digital/seo ^1.1 -> satisfiable by dachcom-digital/seo[v1.1.0, v1.1.1].
 ```

**Comment by bitfactory-timon-vandermeulen** [comment]
Is there any sight on when this upgrade will happen? There seems to be a fork that has implemented (a part of) the upgrade so maybe that's usefull?

https://github.com/fracsi/pimcore-seo

**Comment by solverat** [comment]
See #24

**Comment by solverat** [comment]
Done! https://github.com/dachcom-digital/pimcore-seo/releases/tag/v2.0.0

**Comment by dpfahlbusch** [comment]
Awesome :D
