### ISSUE TITLE
Incompatibility with Pimcore Portal Engine Bundle

### ISSUE THREAD

**Issue by mladenmakso** [dachcom-digital/pimcore-seo#26]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

After installing Pimcore Portal Engine bundle this error popup:

![image](https://user-images.githubusercontent.com/80458166/159893898-4aa7aaa8-4c72-418c-b8d6-1c05d2b8c930.png)

**Comment by solverat** [comment]
That is not an issue related with this bundle. You may have forgotten to import the full namespace `SeoBundle\Model\ElementMetaData`.
