### ISSUE TITLE
Does not use BundleManagerEvents

### ISSUE THREAD

**Issue by dkarlovi** [dachcom-digital/pimcore-seo#29]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Currently, [the best practice direction is to use `BundleManagerEvents` to configure the bundle](https://github.com/pimcore/pimcore/issues/8824), with old structure being obsolete. The bundle as-is currently doesn't listen to bundle manager events to register resources, relying instead on the old mechanism which no longer works in some cases.

**Comment by solverat** [comment]
@dkarlovi While this is correct when it comes to the app itself, a standalone bundle is still allowed to use the `getCssPaths` and `getJsPaths` methods, right? Am I missing something here?

If you're talking about this one: 
![image](https://user-images.githubusercontent.com/700119/201737589-751a88db-20cc-494f-93a2-2f4a5a30bb2e.png)

We're aware of that, SEO Bundle 2.2 is going to support Pimcore >= 10.5 only.
