### ISSUE TITLE
XLIFF Export/Import Support

### ISSUE THREAD

**Issue by valentin-** [dachcom-digital/pimcore-seo#31]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

I'm not sure to report this as bug report/feature request or it it's out of scope or even possible.

When exporting data objects using the pimcore XLIFF export, the seo data won't get exported as they are stored in a separate table. A solution would be handy to add the maintained data to the XLIFF export and save them back to the table on import.

**Comment by solverat** [comment]
This is currently not possible due to import/export restrictions of pimcore. 

I've created an PR for PIMCORE to allow adding custom values to the XLIFF import/export process. 

https://github.com/pimcore/pimcore/pull/13604

**Comment by solverat** [comment]
Since the PR has been accepted for 11.x only, this will be available in 3.0.

**Comment by valentin-** [comment]
Hi @solverat, do you have plans yet to make the extension Pimcore 11 ready?

Thanks!

**Comment by solverat** [comment]
Yes, see https://github.com/dachcom-digital/pimcore-seo/issues/49

**Comment by solverat** [comment]
done with #53
