### ISSUE TITLE
Preview image (og:image, twitter:image) not shown if asset path contains spaces

### ISSUE THREAD

**Issue by IAmMajo** [dachcom-digital/pimcore-seo#35]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

If the asset path of the properties og:image or twitter:image contains spaces no preview image is shown.
![image](https://user-images.githubusercontent.com/35848058/187896968-b6833c19-05bf-4d17-85c5-7e140d879ee0.png)

The background-image style generated by the SEO Bundle is shown as an invalid property value in browsers because the URL contains spaces.
![image](https://user-images.githubusercontent.com/35848058/187898186-5870b355-9d01-4528-9b65-dac309ba04d1.png)

The URL used in the background-image style should be URL encoded and spaces in the asset path should be replaced with `%20`.

**Comment by solverat** [comment]
Fixed in https://github.com/dachcom-digital/pimcore-seo/pull/41
