### ISSUE TITLE
Tab duplicated

### ISSUE THREAD

**Issue by yuliusardian** [dachcom-digital/pimcore-seo#38]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

![Screenshot from 2022-10-13 11-25-56](https://user-images.githubusercontent.com/6629384/195501544-857c8fae-3352-4b94-bead-0dc1aac74832.png)

SEO Sub Tab is duplicated. I do following the documentation for setup the bundle and also installed SchemaBundle, ToolboxBundle too.

**Comment by solverat** [comment]
Duplicate, see #28
