### ISSUE TITLE
Umlauts in markup

### ISSUE THREAD

**Issue by mindbreaker** [dachcom-digital/pimcore-seo#45]
I've noticed an issue with the way umlauts are displayed in Schema Markup. It seems that the umlauts are not formatted correctly and the output is incorrect.

For example, the letter "`ä`" is being displayed as "`\u00c3\u00a4`" in the markup after saving. On the source code the output is: `Ã¤`. When manually inputting special characters, they may not display correctly unless they are entered as HTML entities. This issue does not occur when the input is done through the API, such as in the case of an organization.

**Comment by solverat** [comment]
fixed in #46
