### ISSUE TITLE
Seo Document Editor Support

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-seo#54]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Allow Users to modify title/description via SEO Document Editor (If pimcore seo bundle is installed)

**Comment by solverat** [comment]
done with #53

**Comment by dpfaffenbauer** [comment]
@solverat Can this fix be somewhat be picked to the 10.x compatible version?

**Comment by solverat** [comment]
@dpfaffenbauer currently we don't have any plans to backport it.
