### ISSUE TITLE
Error when adding a thumbnail

### ISSUE THREAD

**Issue by aKugler** [dachcom-digital/pimcore-seo#55]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no

Hi!
I was playing around with your current master in an 11.0.6 today and ran into a bug. My config is the same as https://github.com/dachcom-digital/pimcore-seo/blob/master/docs/00_Setup.md#configuration. When I then wanted to add an image at Open Graph, it came to the 500. 
```
Pimcore\Model\Asset\Image\Thumbnail::getPath(): Argument #1 ($args) must be of type array, bool given, called in /var/www/html/vendor/dachcom-digital/seo/src/Tool/UrlGenerator.php on line 82
```
https://github.com/dachcom-digital/pimcore-seo/blob/master/src/Tool/UrlGenerator.php#L82
https://github.com/pimcore/pimcore/blob/11.x/models/Asset/Image/Thumbnail.php#L47

**Comment by solverat** [comment]
@aKugler thanks for being an early bird tester! :)

fixed!

**Comment by aKugler** [comment]
Holiday and finally time for the important things in life. ;-)

You're welcome and thank you for your work
