### ISSUE TITLE
Error during the installation of the bundle

### ISSUE THREAD

**Issue by aKugler** [dachcom-digital/pimcore-seo#71]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Hi,

i just wanted to install the SeoBundle in a project according to the instructions. composer require, added the line in `config/bundles.php` and then the `bin/console pimcore:bundle:install SeoBundle`. The following error is thrown at the last step:

```The class 'SeoBundle\Model\ElementMetaData' was not found in the chain configured namespaces Pimcore\Bundle\GenericExecutionEngineBundle\Entity```

The project runs under PHP 8.3.6.
pimcore/admin-ui-classic-bundle: 1.6.1
pimcore/data-hub: 1.8.2
pimcore/data-importer: 1.9.4
pimcore/pimcore: 11.4.1
pimcore/platform-version: 2024.3

Incidentally, I have the same problem with the FormBuilderBundle. Can you please help me and tell me what I have forgotten? Unfortunately, I can't see the wood for the trees at the moment.

Many thanks and best regards

**Comment by mtramp-neusta** [comment]
Hello there,
i had the same Problem. Registering it **manually** in the **Kernel.php** worked for me.

**Comment by solverat** [comment]
@aKugler That's a pimcore issue. I've already posted a solution (and explanation) here:

https://github.com/pimcore/generic-data-index-bundle/issues/209#issuecomment-2346149161
