### ISSUE TITLE
License Change

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-seo#73]
Dear Contributors, 

we're currently working on dual licensing this bundle (under GPLv3 and DCL [`DACHCOM Commerce License`]) to be compatible with Pimcore Enterprise and Professional. In order to do that, we need your approval (contributor license agreement). The agreement can be found here: https://github.com/dachcom-digital/pimcore-seo/blob/master/CLA.md

We therefore kindly ask the following persons to sign the CLA by **writing the following sentence as a comment under this issue**:

`I have read the CLA Document and I hereby sign the CLA`

- [x] @NiklasBr
- [x] @dpfaffenbauer
- [x] @breakone
- [x] @pascalmoser
- [x] @dkarlovi
- [x] @fracsi
- [x] @vmalyk

**Comment by dpfaffenbauer** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by NiklasBr** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by breakone** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by fracsi** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by pascalmoser** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Zodiarc** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by vmalyk** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dkarlovi** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by solverat** [comment]
Thanks to all of you for your help! ❤️
